### ISSUE TITLE
Allow for multi-value fields

### ISSUE THREAD

**Issue by tmtmtmtm** [tmtmtmtm/csv_to_popolo#90]
We should be able to note that a column has a `multivalue_separator` to signify that it holds a list of values, rather than just a single value. 

For example:

```
    email: {
      type: 'asis',
      multivalue_separator: ';',
    },
```

And then the source could have `f.blogs@official.gov;fredbloggsMP@gmail.com` as an `email` value.

Then, when extracting the data from any such field, we should split on the separator, and build up a list of values for it, rather than assuming it will only have one (similarly to what we've currently hard-coded for `alternate_names`).

**Comment by tmtmtmtm** [comment]
Having separators like this is part of the CSV on the Web spec (https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/), so it's possible there may be a reference implementation of parsing such data somewhere already that takes care of any gotchas (like the separator needing to be quoted if it's also used within the string). But I think we're OK with a fairly naïve implementation at this point as we effectively control both ends of the process, and can ensure we don't supply values where that's a problem.

**Comment by mhl** [comment]
Just to check, in the email example, would you expect the output to be:

``` json
{
    "email": "f.blogs@official.gov",
    "contact_details": [
        {
            "type": "email",
            "value": "fredbloggsMP@gmail.com"
        }
    ]
}
```

?

**Comment by tmtmtmtm** [comment]
Gah, I forgot that `email` is a degenerate case in Pombola. That's probably not a great first example then, because of that. I think I'd treat the top-level `email` as a short-cut for the primary email (or just the first one given), but include them all in the `contact_details`. I think with WriteIt, for example, we assumed the logic should be "If there's a `contact_details` section use that; if that's missing/empty, check if there's a top level `email`"

So I'd expect something more like:

```
{
    "email": "f.blogs@official.gov",
    "contact_details": [
        {
            "type": "email",
            "value": "f.blogs@official.gov"
        },
        {
            "type": "email",
            "value": "fredbloggsMP@gmail.com"
        }
    ]
}
```
